app/models.py
from datetime import datetime

from flask_login import UserMixin
from . import db,login_manager
from werkzeug.security import generate_password_hash, check_password_hash


class RandQuotes:


  def __init__(self,author, quote):
      self.author = author
      self.quote = quote



@login_manager.user_loader
def load_user(user_id):
  return User.query.get(int(user_id))
class User(UserMixin, db.Model):
  __tablename__ = 'users'

  id = db.Column(db.Integer, primary_key=True)
  username = db.Column(db.String(128), nullable=False)
  email = db.Column(db.String(128), nullable=False, unique=True)
  pass_code = db.Column(db.String(128), nullable=False, unique=True)
  blogposts = db.relationship('BlogPost', backref='user', lazy='dynamic')
  comments = db.relationship('Comment', backref='user', lazy='dynamic')

  @property
  def password(self):
    raise AttributeError('You cannot access this password')


  @password.setter
  def password(self, password):
    self.pass_code = generate_password_hash(password)


  def verify_password(self, password):
    return check_password_hash(self.pass_code, password)


  def __repr__(self):
      return f'User {self.username}'




class BlogPost(db.Model):
  __tablename__ = 'blogposts'

  id = db.Column(db.Integer, primary_key=True)
  title = db.Column(db.String(255), nullable=False)
  category = db.Column(db.String, nullable = False)
  post = db.Column(db.String, nullable=False)
  date = db.Column(db.DateTime, default=datetime.now())
  user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
 


  def __repr__(self):
      return f'User {self.post}'


class Comment(db.Model):

  __tablename__ = 'comments'

  id = db.Column(db.Integer, primary_key=True)
  comment = db.Column(db.String)
  user_id = db.Column(db.Integer, db.ForeignKey('users.id'))



  def __repr__(self):
      return f'User {self.comment}'



  

app/main/forms.py
from flask_wtf import FlaskForm
from sqlalchemy import Text
from wtforms import StringField,SelectField,TextAreaField, SubmitField
from wtforms.validators import DataRequired



class BlogForm(FlaskForm):
  title = StringField('Title:', validators=[DataRequired()])
  category = SelectField('Category:', choices=[('Lifestyle'), ('Design'), ('Career')])
  post = TextAreaField('Your post:', validators=[DataRequired()])
  submit = SubmitField('Post')


class CommentForm(FlaskForm):
  comment = TextAreaField('Your Comment:', validators=[DataRequired()])
  submit = SubmitField('Post')

app.py
from app import create_app
# from flask_script import Manager,Server
from app import db
from app.models import User
from flask_migrate import Migrate




app = create_app('production')
# manager = Manager(app)
migrate = Migrate(app,db)

# manager.add_command('server', Server)



# @manager.shell
# def create_shell_context():
#   return dict(app=app, db=db, User=User)




if __name__ == '__main__':
  app.run()

app/__init__.py
from flask import Flask
from config import config_options
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager

bootstrap = Bootstrap()
db = SQLAlchemy()
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'


from . import models
def create_app(config_name):


  app = Flask(__name__)



  #app configurations
  app.config.from_object(config_options[config_name])

  from .requests import configure
  configure(app)


  #initialise extension
  bootstrap.init_app(app)
  db.init_app(app)
  login_manager.init_app(app)


  #register blueprint
  from app.main import main as main_blueprint
  app.register_blueprint(main_blueprint)
  from app.auth import auth as auth_blueprint
  app.register_blueprint(auth_blueprint)



  return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, forms, error

app/main/views.py
from flask_login import current_user, login_required
from app import db
from app.main.forms import BlogForm, CommentForm
from app.models import BlogPost, Comment
from . import main
from flask import render_template, url_for, request, redirect
from ..requests import get_random_quotes



@main.route('/')
def index():
  rand_quote = get_random_quotes()
  title = "Welcome to my personal blogs | Be Inspired"
  return render_template('index.html', quote=rand_quote, title=title)



@main.route('/new-post', methods=['POST', 'GET'])
@login_required
def new_post():
  title = 'PersonalBlog | Create a new Blog post.'
  form = BlogForm()
  if form.validate_on_submit():
    title=form.title.data
    category=form.category.data
    post=form.post.data
    user_id=current_user._get_current_object().id

    new_post_obj=BlogPost(title=title, category=category, post=post, user_id=user_id)
    db.session.add(new_post_obj)
    db.session.commit()
    
    return redirect(url_for('main.blogs_page'))

  return render_template('new_post_form.html', title=title, post_form=form)


@main.route('/posts', methods=['GET'])
def blogs_page():
  title='PersonalBlog | Blog posts'
  blogs =  BlogPost.query.all()

  return render_template('blogs.html', title=title, blogs=blogs)


@main.route('/comments/<int:blogpost_id>', methods=['POST', 'GET'])
@login_required
def new_comment(blogpost_id):
  title = 'PersonalBlog | Leave a Comment'
  comments = Comment.query.all()
  form = CommentForm()
  if form.validate_on_submit():
    comment = form.comment.data
    user_id = current_user._get_current_object().id

    new_comment_obj = Comment(comment=comment, user_id=user_id)
    db.session.add(new_comment_obj)
    db.session.commit()
    return redirect(url_for('main.new_comment', blogpost_id=blogpost_id))

  return render_template('comment_form.html', comment_form=form, title=title, comments=comments)

@main.route('/delete/<int:comment_id>')
def delete_comment(comment_id):
  comment = Comment.query.filter_by(id=comment_id).first()
  db.session.delete(comment)
  db.session.commit()

  return redirect(url_for('main.new_comment'))

app/templates/base.html
{% extends 'bootstrap/base.html' %}


{% block styles %}
{{super()}}
  <link rel="stylesheet" href="{{url_for('static', filename='css/index.css')}}">
{% endblock %}

{% block scripts %}
<script src="https://kit.fontawesome.com/85217334a5.js" crossorigin="anonymous"></script>
  {{super()}}
{% endblock %}

app/templates/blogs.html
{% extends 'base.html' %}
{% import 'macros.html' as macro %}

{% block navbar %}
  {% include 'navbar.html' %}
{% endblock %}

{% block content %}
<div class="container-fluid">
  <div class="row blog-banner">
    <div class="col-md-4"></div>
    <div class="col-md-4" style="display: grid; place-items:center; min-height:50vh;">
      <h1 style="text-align: center; font-weight:bold;  color:#F6464E"><span class="bg-text">OUR</span> BLOGS</h1>
    </div>
    <div class="col-md-4"></div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-10" style="background-color: #F2F9FF; padding: 0 5vh;">
      {{macro.displayBlog(blogs)}}
    </div>
    <div class="col-md-1"></div>
  </div>
</div>
{% endblock %}

app/templates/comment_form.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as  wtf %}
{% import 'macros.html' as macro %}


{% block navbar %}
{% include 'navbar.html' %}
{% endblock %}


{% import 'macros.html' as macro %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-md-2"></div>
        <div class="col-md-4 leave-com">
          {{macro.displayComment(comments)}}
        </div>
        <div class="col-md-4">
        <h2 style="text-align: center; margin-bottom: 10vh;"><span class="bg-text">LEAVE</span> A COMMENT</h2>
          {{wtf.quick_form(comment_form)}}
        </div>
      <div class="col-md-2"></div>
    </div>
  </div>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}

{% block navbar %}
  {% include 'navbar.html' %}
{% endblock %}

{% block content %}
  <div class="banner container-fluid">
    <div class="row">
      <div class="col-md-6 display">
        <h4 style="font-weight: bold;"><span class="bg-text">DAILY</span> QUOTES <i class="fas fa-angle-double-right"></i></h4>
        <blockquote class="blockquote-inverse mb-0">
          <p style="font-size: 180%; font-weight:bold;">{{quote.quote}}</p>
          <footer class="blockquote-footer">By <cite title="Source Title">{{quote.author}}</cite></footer>
        </blockquote>
      </div>
      <div class="col-md-6">
        <img src="../static/images/Inspire.jpeg" class="inspire rounded" alt="">
      </div>
    </div>
  </div>

  <div class="container">
    <div class="row newsletter"  style="margin-top: 15vh;">
      <div class="col-md-6" style="padding: 2vh 1vh ;">
        <h3 style="font-weight:bold ;">Subscribe to my Newsletter</h3>
        <p style="color:#969694;">For weekly updates and latest blogs</p>
      </div>
      <div class="col-md-6" style="padding: 2vh 1vh ;">
        <div class="input-group" style="padding-top: 3vh;">
          <input type="text" name="sub" class="form-control" placeholder="Enter email address">
          <button  type="button" class="btn btn-dark">Subscribe</button>
        </div>
      </div>
    </div>
  </div>

  <div class="container" style="margin-top:10vh ;">
    <h2 class="heading">Featured articles</h2><hr>
    <div class="row" style="margin:auto ;">
      <div class="col-md-4">
        <div class="card mb-3">
          <img src="../static/images/pexels-photo-7525029.jpeg" class="card-img-top" alt="...">
          <div class="card-body">
            <h6 class="card-title">LIFESTYLE</h6>
            <p class="card-text heading">Believed to be the root cause of 90% of all illnesses, stress is defined as your body’’s response to any type of change that causes physical, emotional, or psychological strain.</p>
            <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
          </div>
        </div>
      </div>

      <div class="col-md-4">
        <div class="card mb-3">
          <img src="../static/images/Inspire.jpeg" class="card-img-top" alt="...">
          <div class="card-body">
            <h6 class="card-title">CAREER</h6>
            <p class="card-text heading">If you’re looking to get some career inspiration in the new year, ramping up your reading list is one of the best places to start.</p>
            <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
          </div>
        </div>
      </div>

      <div class="col-md-4">
        <div class="card mb-3">
          <img src="../static/images/pexels-photo-4705144.jpeg" class="card-img-top" alt="...">
          <div class="card-body">
            <h6 class="card-title">LIFESTYLE</h6>
            <p class="card-text heading">A career change can seem tricky to someone who hasn’t done it before. Believe me, I was skeptical the first time I tried to get a job outside of the nonprofit field. But my own experience with looking to change careers gave me skills that I’ve carried over into every job I’ve had since.</p>
            <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
          </div>
        </div>
      </div>


    </div>
  </div>
  <div class="container" style="margin-top:15vh ;">
    <h2 class="heading">Recent articles</h2><hr>
    <div class="row">
      <div class="col-md-8">
        <div class="card mb-3">
          <img src="../static/images/pexels-photo-999267.jpeg" class="card-img-top" alt="...">
          <div class="card-body">
            <h6 class="card-title">CAREER</h6>
            <p class="card-text heading">The rules for workplace behavior have changed. With all the modern conveniences, connections and companies we have at our fingertips and in our lives every day, the old Emily Post rulebook gets tossed out the window.</p>
            <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
          </div>
        </div>

        <div class="card mb-3">
          <img src="../static/images/pexels-photo-3094211.jpeg" class="card-img-top" alt="...">
          <div class="card-body">
            <h6 class="card-title">LIFESTYLE</h6>
            <p class="card-text heading">If you and a group of friends are approaching your gap year, it is traditional to see a bit of the world, and, of course, there are many ways that you can learn about other cultures by travelling...</p>
            <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
          </div>
        </div>
      </div>

      <div class="col-md-4">
        <h2 class="heading">About Me</h2><hr>
        <div class="card mb-3">
          <img src="../static/images/CROP_1637176140839.jpg" class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title heading" style="padding-top:3vh; text-align:center; font-size: 1.2em;">CHARLES OKUNZO</h5>
            <p class="card-text" style="text-align:center; color: #969694;">Junior Delevoper at Moringa School</p>
            <p class="card-text" style="text-align:center;"><small class="text-muted">Since Jan 2022</small></p>
          </div>
        </div>

        <div class="card" style="margin-top:15vh ;">
          <img src="../static/images/pexels-photo-4466381.webp" alt="" class="img-responsive">
        </div>
      </div>
    </div>
  </div>

  <footer class="container-fluid center-block footer" style="text-align:center ;">
    <div class="col-md-6">
      <ul class="nav navbar-nav">
        <li><a href="/">Home</a></li>
        <li><a href="" >About</a></li>
        <li><a href="{{url_for('main.blogs_page')}}">Blogs</a></li>
    </ul>
    </div>
    <div class="col-md-6">
      <p>
        <i class="fab fa-facebook"></i>
        <i class="fab fa-twitter"></i>
        <i class="fab fa-linkedin-in"></i>
      </p>
    </div>
  </footer>
{% endblock %}

app/templates/macros.html
{% macro displayBlog(blogs) %}
{% if blogs %}
  {% for blog in blogs %}
   <div style="margin:10vh 0 ;">
    <h5><span class="bg-text">{{blog.category}}</span></h5>
    <h2 style="font-size:1.5em; font-weight: bold;">{{blog.title}}</h2>
    <small style="padding: 8vh 0;">Posted on {{blog.date}}</small>
    <footer class="blockquote-footer">By <cite title="Source Title">{{blog.user.username}}</cite></footer>
    <p>
      {{blog.post}}
    </p>
    <p style="padding:5vh 0 ;"><a href="{{url_for('main.new_comment', blogpost_id=blog.id)}}"><i class="fa-solid fa-comments"></i> Leave a comment</a></p>
    <hr>
   </div>
  {% endfor %}
  {% else %}
        <h5 style="text-align: center; font-size:1.5em;">No blogs Posted yet. <a href="{{url_for('main.new_post')}}"><i style="text-align:center ;color: #F6464E;" class="fa-solid fa-plus"></i> Add blogs</a></h5>
  {% endif %}
  {% endmacro %}

  {% macro displayComment(comments) %}
  {% if comments %}
  {% for comment in comments %}
    <div class="card">
      <div class="card-body">
        <blockquote class="blockquote mb-0">
          <p>{{comment.comment}}</p>
          <footer class="blockquote-footer">By <cite title="Source Title">{{comment.user.username}}</cite></footer>
          
            <p><a href="{{url_for('main.delete_comment', comment_id=comment.id)}}" title="Delete comment"><i class="fa-solid fa-trash-can"></i></a></p>
          
        </blockquote>
      </div>
    </div><hr>
    {% endfor %}
    {% else %}
    <h3>No comments posted yet</h3>

    {% endif %}

{% endmacro %}

app/templates/navbar.html
<div class="navbar" role="navigation">
  <div class="container-fluid">
      <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/"><span class="bg-text">PERSONAL</span>BLOG</a>
      </div>
      <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
              <li><a href="/">Home</a></li>
              <li><a href="" >About</a></li>
              <li><a href="{{url_for('main.blogs_page')}}">Blogs</a></li>
              {% if current_user.is_authenticated %}
              <li><a href="{{url_for('main.new_post')}}">Post Blog</a></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Signed In<span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><a href="#">Signed In as {{current_user.username}}</a></li>
                  <li role="separator" class="divider"></li>
                  <li><a href="{{url_for('auth.signout')}}">Sign Out</a></li>
                </ul>
              </li>
              {% else %}
              <li><a href="{{url_for('auth.signup')}}">Sign Up</a></li>
              <li><a href="{{url_for('auth.signin')}}">Sign In</a></li>
              {% endif %}
          </ul>
      </div>

  </div>
</div>

app/templates/new_post_form.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block navbar %}
  {% include 'navbar.html' %}
{% endblock %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-md-2"></div>
      <div class="col-md-8">
        <h2 style="padding:5vh 0 ;"><span class="bg-text">CREATE</span> NEW BLOG</h2>
        {{wtf.quick_form(post_form)}}
      </div>
      <div class="col-md-2"></div>
    </div>
  </div>
{% endblock %}